### ISSUE TITLE
Enhance retry/timeout functionality

### ISSUE THREAD

**Issue by jsw** [istio/old_issues_repo#251] opened 2018-03-25 20:19 UTC
Feature request

**Describe the feature:**

Istio should expose at least as much config as envoy proxy supports. One apparently missing feature is configuring the `retry-on` policy https://www.envoyproxy.io/docs/envoy/v1.6.0/configuration/http_filters/router_filter.html#config-http-filters-router-x-envoy-retry-on

Additional parameters that would be useful
* connect timeout
* socket/read/idle timeout (maximum time to wait between packets)

**Comment by sakshigoel12** [comment] 2018-04-23 21:18
@costinm can you update this issue

**Comment by costinm** [comment] 2018-05-21 21:56
We can try to get it for 1.0 - 0.8 has too much churn.

**Comment by louiscryan** [comment] 2018-06-22 22:58
Duplicate of #235

**Closed by louiscryan** 2018-06-22 22:58 UTC
Labels: area/networking, kind/customer issue
